### ISSUE TITLE
Feature request - Way to track sanger confirmation results and signatures

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [woook/moka-fe#140]
At the moment we track sanger confirmation results and signatures on an excel that we upload into Moka results page. Could this be built into Moka instead?

**Comment by andyb3** [comment]
Need to discuss requirements

**Comment by AmyAmelia** [comment]
Issue #185 WES: Need a method to identify/ track when a completed test is having further Sanger analysis on Parental samples overlaps. Will close #185.

**Comment by AmyAmelia** [comment]
Added to smart-sheet, pending project prioritisation meeting.
