### ISSUE TITLE
WES results page - cannot add files before batching

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [woook/moka-fe#144]
I tried to add an email to a newly ordered sample but got a message that it needed to be batched first. Is there a reason for this restriction?

**Comment by andyb3** [comment]
Attached files are grouped by WES batch on the F: drive to keep the folder organised. Possible could change this to group by something else (e.g. date requested) instead.

**Comment by MattiasJanssonviapath** [comment]
This is not a huge issue, we very seldom want to attach something before they are batched, and we can make a note to attach later when batched. 
What happens if we swap batch for a sample, though?

**Comment by andyb3** [comment]
If you changed WES batch, the previously uploaded files would remain the previous WES batch folder, but they would still be associated with the correct WES test, and the link to the files would still work. Any new files uploaded after the switch would be uploaded to the 'new' WES batch folder.

**Comment by MattiasJanssonviapath** [comment]
I have a case that will not be batched due to the sister being tested instead, and now I can't attach the email thread to the original sister. Could you implement an "unbatched" folder if, as you say above, the link will not change anyways?
