### ISSUE TITLE
Unable to add new panels when when exisiting PanelCode is NULL 

### ISSUE THREAD

**Issue by andyb3** [woook/moka-fe#153]
PanelCode field in NGSPanel table is a unique index. The PanelCode is not auto-generated until the user enters check 1 initials. If the user exits before PanelCode is generated, further panels cannot be created because of the duplicate NULL panel code.

Possible solutions: 

- Remove Unique restriction from field

- have PanelCode generated when category/sub-category entered.

**Comment by woook** [comment]
I have changed the index on ```PanelCode``` to be a non-unique one. 
Will close this issue now.
