### ISSUE TITLE
new moka query for my RNAs project

### ISSUE THREAD

**Issue by mikecoldwell** [woook/moka-fe#179]
Hi
Please can I have a new moka query similar to 92241FetalBloodDNAs but with samples that failed first time instead of passed. This would be very much appreciated.
See below for background
Thank you very much
Mike 

Hi Wook
Please can I have a new moka query for my RNAs project?
As mentioned at the array projects meeting, the RNAse project has slightly stalled. Although the DNAs looked much better on a gel than before the RNAse digest, when we repeated the hyb the data was no better. We want to select samples that failed and I now believe the original query (92241FetalBloodDNAs created to aid runsheet creation) only pulls out samples that passed on array.  Andy created an additional query which was supposed to be the same as 92241FetalBloodDNAs except it pulls out things that did not have a Normal result code, however this query seems to have pulled out only a small number of samples most of which are not fetal blood samples.
 
The actual practical part of this project is very easy and it would be a shame not to know whether it can improve our results.
 
Thank you very much
 
Mike

**Comment by andyb3** [comment]
Resolved
