### ISSUE TITLE
WES results: VCF import. display saying 'none' under each panel

### ISSUE THREAD

**Issue by AmyAmelia** [woook/moka-fe#196]
pop up displaying which file shall be imported under each panel (primary, secondary or tertiary) stated 'None' dispite vcf being saved in the correct loaction and named correctly.
When clicking 'OK', vcf imported fine and populated MOKA variant table.

**Comment by andyb3** [comment]
Could you let me know the NGSTestID for the sample?

**Comment by andyb3** [comment]
See NGSTest 578
