### ISSUE TITLE
Ingenuity File Sharing - use generic bioinformatics email address 

### ISSUE THREAD

**Issue by SueLillis** [woook/moka-fe#201]
Could the gst-tr.MokaGuys@nhs.net  email address be used as the Ingenuity Admin account?
This way anyone from the bioinformatics team can share Ingenuity files rather than just relying on Wook. 
Discussed at WES/Bioinformatics meeting on 01/08/17

**Comment by aledj2** [comment]
wook's account can now be accessed by other members of the bioinformatics team
