### ISSUE TITLE
Ingenuity WES cases - share pls

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [woook/moka-fe#221]
We are getting low on available WES cases and need more shared with us in Ingenuity. Share with Matt, Sue and Rachael Irwin.

Cheers, /Matt

**Comment by woook** [comment]
Please could you tell us which WES batches you would like shared with you?

**Comment by MattiasJanssonviapath** [comment]
WES14 except for DNA number 167726, 169098, and 181158

**Comment by AmyAmelia** [comment]
Shared to Matt
