### ISSUE TITLE
Coverage report TestID 558

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [woook/moka-fe#222]
Number of genes issue.
Promised report in August.

Cheers /Matt

**Comment by aledj2** [comment]
The gene panel includes genes which are phenotype locus only. These genes can be excluded from the report. 
see code changes in automatecoveragereports repository

**Comment by aledj2** [comment]
see 004b16d4d654ca0c3e06f6c9dc4cd82d4bd2e954
