### ISSUE TITLE
WES coverage : NGStest 308

### ISSUE THREAD

**Issue by AmyAmelia** [woook/moka-fe#223]
Sample was rerun due to initial poor coverage. Coverage report is being generate using old run data.
repeat run= NGS160A_03_160179_AH_WES_S3_R1_001_combined
MultiQC date : 170411

**Comment by aledj2** [comment]
NGSTest 389 was also re-run (WES14)

**Comment by aledj2** [comment]
NGSTest389 has been reported so no need to re-do coverage report

**Comment by aledj2** [comment]
NGS test 308 was re-run and then the had the fastq files merged. for somereason coverage was performed on this bam file using Pan1092, not 493. Will repeat coverage and then import this to moka
