### ISSUE TITLE
WES Coverage report

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [woook/moka-fe#235]
Coverage report for TestID 419 was done on the old failed run (NGS138B) rather than on the combined QXT run (NGS160A_02_165286_LT_WES_S2_R1_combined - Date 170411 in http://stickie.be/b/fastqc/)

**Comment by aledj2** [comment]
repeating coverage using the BAM file from the run using the fastq files combined from two sequencing runs (the data used to do the analysis).

This coverage data will need replacing in moka

**Comment by aledj2** [comment]
Moka now contains correct coverage data
