### ISSUE TITLE
WES - DNA not visible

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [woook/moka-fe#236]
In DNA QC when assigning DNA, the DNA for TestID 899 is not visible. When opening the patient page and using Check GW for DNA, the DNA is already imported into Moka. Still not visible under DNA Aliquotes tab or DNA QC.

**Comment by andyb3** [comment]
It appears that this patient has two different PRU numbers. @MattiasJanssonviapath please could you speak to the office staff and ask them to perform a merge?

**Comment by MattiasJanssonviapath** [comment]
Any progress on this issue?

Cheers, /Matt

**Comment by andyb3** [comment]
Will try and get this sorted today

**Comment by andyb3** [comment]
Hi Matt,

Can you check if you can see the DNA now?

**Comment by MattiasJanssonviapath** [comment]
Hi Andy,

Yes, the DNA is visible now. :)

Cheers, /Matt
