### ISSUE TITLE
Mako access

### ISSUE THREAD

**Issue by divyaswift** [woook/moka-fe#241]
Dear Wook,

Could you please provide me access to import VCFs files into moka, when i try to import from ingenuity it says my access is denied. 
Please let me know if you need more information  regarding this.

Many thanks,
 
Divya Vasanth| Viapath
Healthcare Scientist
Cancer Genetics
Genetics Department|5th Floor Tower Wing| Guy's Hospital| London SE1 9RT 
0207 188 1703
020 7188 1697 (Fax)
Divya.Vasanth@gstt.nhs.uk
www.viapath.co.uk

**Comment by woook** [comment]
Hi Divya - are you able to enter other information into Moka? Or can you edit stuff in Moka?

**Comment by divyaswift** [comment]
Hi Wook, I can enter informations and also can edit stuffs.
thank you

**Comment by divyaswift** [comment]
Hi Wook,
Any updates regarding this?
Divya

**Comment by aledj2** [comment]
I'm afraid we have to wait until people are back from annual leave before this can be investigated. If for any reason the workaround fails please let us know. (You could also try logging in as yourself on another PC to see if you get the same error message)

**Comment by divyaswift** [comment]
Hi Wook,

I will let you know when i do this tomorrow.

Thanks
Divya Vasanth

________________________________

**Comment by aledj2** [comment]
cannot import variants from vcf - assess if user has sufficient write access to moka??

**Comment by divyaswift** [comment]
Hi,
Any update regarding this issue?

**Comment by andyb3** [comment]
Access is denied to the Genetics_Data2 so can't use python.

**Comment by andyb3** [comment]
I'm going to close this issue, but please re-open it the problem doesn't get fixed.
