### ISSUE TITLE
New control embryo for EvE

### ISSUE THREAD

**Issue by schuiie** [woook/moka-fe#242]
Hello!

Can we change our default magic embryo for EvE in Moka under PGD menu 'EvE on whole run' and 'Run EvE manually'? The details of the default embryo can be found in the excel file located here:
S:\Genetics_Data2\Array\Audits and Projects\170727 Livebirth MDA PGD embryos to be used for EvE

Thanks!

**Comment by aledj2** [comment]
252846912916.4 cy5

**Comment by aledj2** [comment]
Have changed the default values on form 2022 EvEManual in db in aled_dev. May be worth making these changes again rather than importing the form.
