### ISSUE TITLE
NGS182A inactive sample

### ISSUE THREAD

**Issue by KristinaStone** [woook/moka-fe#243]
Hi, Can you please make the following sample active on Ingenuity? NGS182A_16_186845_LS_BRCAv2_Pan1449_S16_R1_001
Thanks, Kristina

**Comment by aledj2** [comment]
This sample has most likely been delayed because the gst-tr.interpretation.request​ Ingenuity account is over the quota of 200 samples.  If you could encourage the removal of any samples that are no longer needed that would help. We will also do this to all other Ingenuity users

**Comment by aledj2** [comment]
it is now active
