### ISSUE TITLE
New EK in Moka

### ISSUE THREAD

**Issue by divyaswift** [woook/moka-fe#245]
Hi
I am unable to create new EK number in moka, for this Spec no.17/27612 only, tried with three different username & different PCs as well.
Please could you look into this asap.
thanks
Divya Vasanth

**Comment by aledj2** [comment]
This case has been fixed. It was because of an apostrophe in the name. However this will happen again for any patients with apostophes in the name.

A issue to implement a permenant fix has been raised.
