### ISSUE TITLE
NGS182B data on Ingenuity

### ISSUE THREAD

**Issue by KristinaStone** [woook/moka-fe#247]
Hi, Can you please upload the data for NGS182B sample 42 and 46 onto Ingenuity? Also, there seems to be a duplicate for NGS182B sample 36. Thanks, Kristina

**Comment by aledj2** [comment]
Samples 42 and 46 should now be there.
Feel free to delete one of the copies of sample 36. Will look into how that became duplicated

**Comment by aledj2** [comment]
DNA Nexus have suggested an explanation behind the issues with Ingenuity import but not much we can do about it - it's the "network"
