### ISSUE TITLE
DNA NGSEQ2 Panel

### ISSUE THREAD

**Issue by rachaelmein** [woook/moka-fe#253]
Has the BED file been made for the DNA NGSEQ2 panel (Pan1158 Variant/Pan1456 CNV)?

If so please could the validation samples be analysed through DNA Nexus.  They are NGS171B run number is 170616_NB551068_0051_AHHNL2BGX2_SampleSheet.csv
Thanks

**Comment by aledj2** [comment]
awaiting code review

**Comment by aledj2** [comment]
done
