### ISSUE TITLE
RPKM for FH and Alports

### ISSUE THREAD

**Issue by rachaelmein** [woook/moka-fe#258]
The data for RPKM of the control sites is shifted one cell to the left as there is no gene number as there is for the FH exons.  Is there any way of ensuring that the data for the control sites is correctly aligned under the approprirate sample.

**Comment by aledj2** [comment]
The fix might take a while so if you can put together a work around for now. The fix will involve creating new pan numbers for the control sites, then remaking the CNV bed files (also with new Pan numbers).

**Comment by aledj2** [comment]
Hi Rachael,
Are you still ok with the workaround in the RPKM template for these CNV panels?

**Comment by rachaelmein** [comment]
Hi Aled
Remind me what this is?  Does this refer to the fact that we have to insert a column next to the CNV controls so that the data is in line with the rest of the RPKM?  I guess we are OK to keep doing this if it is a hassle to fix.  Obviously it would be better to not have to move the data but we are OK to do this if need be.
Thanks
Rachael

**Comment by aledj2** [comment]
Yea, that's the problem.

We'll re-make the bed files but they'll have a new Pan number.

Will keep you updated.

Aled

Aled Jones
Clinical Bioinformatician
Genetics Laboratories| 5th Floor Tower Wing | Guy's Hospital | Great Maze Pond | London | SE1 9RT
Tel: 02071881701
Email: aledjones@nhs.net
________________________________

**Comment by aledj2** [comment]
These will be replaced by NGSEQ2 so no need to re-make
