### ISSUE TITLE
WES manual coverage report

### ISSUE THREAD

**Issue by hkuoppamaa** [woook/moka-fe#263]
An error message popped up when trying to create a coverage report through Moka, probably because it's a fetal sample and there is no DOB. Could the coverage report be done manually please? The patient is PRU 356832:02 on WES6.

**Comment by aledj2** [comment]
Hi Heidi, Can you try again now please

**Comment by hkuoppamaa** [comment]
Hi Aled,

I tried again and now a different error message popped up. It says: The following output was observed when generating coverage report: \\gstt.local\Shared\Genetics_Data2\Array\Software\Python\python.exe: can't open file 'F:\Moka\Files\Software\depthofcoverage\AutomateCoverageReports\Generate_external_reports.py': [Errno 2] No such file or directory

**Comment by hkuoppamaa** [comment]
The same error message came up when I tried to generate a coverage report for a different patient (PRU 350478:01). Might be a problem with my profile/settings?

**Comment by aledj2** [comment]
hmm, yea that's weird.
It has worked for me. Can you access the S drive ok? (try S:\Genetics_Data2\Array\Software)

In trying to test it out I've made the report for 356832:02.
A coverage report already exists for 350478:01 but I can remake it for you in the short term if required

**Comment by hkuoppamaa** [comment]
Accessing the S drive doesn't seem to be the problem. If you could remake the coverage report for 350478:01 that would be great. I've added a gene to the tertiary panel which is why a new one is needed.

**Comment by aledj2** [comment]
ok, that's done, please check if the extra gene has been added

**Comment by aledj2** [comment]
can you try disconnecting and re-connecting to the field worker access please. Has it ever worked for you?

**Comment by hkuoppamaa** [comment]
Thanks Aled, the extra gene has been added.
I have tried re-connecting to the FWA but that doesn't make a difference. I have never succesfully generated a coverage report. The first time I tried and it didn't work I raised this issue here.

**Comment by aledj2** [comment]
Weird... Are you able to import vcfs from Ingenuity into Moka?

**Comment by aledj2** [comment]
ah, I think I know the issue. Hopefully the fix will be issued shortly but in the mean time feel free to give us/Sue/Matt a shout to generate any further reports 

(change any reference to the S and P drive to the full directory path (gstt.local/shared/etc) on form s_0901

**Comment by hkuoppamaa** [comment]
Haven't tried importing vcf's yet.
Great, no problem, I will ask someone to generate coverage reports for me for now.

**Comment by andyb3** [comment]
Soon to move to new field worker access system so not going to try and fix this now.
