### ISSUE TITLE
Coverage report generation - error message

### ISSUE THREAD

**Issue by SueLillis** [woook/moka-fe#264]
Error message when trying to create coverage report for PRU405555:01 
Message says: Traceback (most recent call last):   NameError: global name "exception" is not define.
I have saved a screen shot of this error message into the test files section of Moka entry

**Comment by SueLillis** [comment]
Error messages also when tried to generate coverage reports for PRU359759:01 and PRUPRU399168

**Comment by aledj2** [comment]
Hi Sue, NGS Tests 664 and 618 have issues with the numbers of genes in the panel not matching the number of genes on the report. I haven't investgated further yet but they both have pan894.

will update on test 568 (399168) later

**Comment by aledj2** [comment]
so there are four genes which are in Pan894 but do not have coordinates, these are 
HTC1 (HGNC:5277)
HTC2 (HGNC:5278)
IGHG3 (HGNC:5527)
PCOS1 (HGNC:8741)

**Comment by aledj2** [comment]
Panel 892 used for Test 568 contains a MT-DNA gene, which we do not test and do not calculate coverage  for.

For all of the genes identified here I suggest removing them from the gene panel are you happy for us to do this?

**Comment by SueLillis** [comment]
Thanks Aled
Yes happy to remove these from panel

**Comment by aledj2** [comment]
deleted. 
You can try making the reports now.
Thanks

**Comment by aledj2** [comment]
(don't close until have adressed all other problem genes - maybe stop these genes from being added to panel in 1st place?)

**Comment by aledj2** [comment]
this should be fixed now

**Comment by aledj2** [comment]
see f8c9e771c3e8c08455f1d37acfac8e56bbf20eab
