### ISSUE TITLE
56G pipeline

### ISSUE THREAD

**Issue by nfoot** [woook/moka-fe#270]
Currently we are using a manual process, which is in the development stage, for analysis of teh Swift 56 gene panel. The flanking file is a work in progress. We have done two runs so far.

We are aiming to bring this into diagnostics early next year and the clinicians are keen this is moved forward in a timely fashion.

Please can an automatic pipeline be developed that is similar to the Swift 5 panel - that can run on the cloud and pass teh VCFs directly to Ingenuity.

If Moka will need some amendments to deal with teh 56G VCFs then please can this also be done.

Thanks
Nicky

**Comment by woook** [comment]
Dear Nicky

Please could this be taken to the R&D meeting for setting a priority.

Thanks,


Wook

**Comment by nfoot** [comment]
Sure - I have submitted it now so there is a formal request for consideration ahead of the R&D meeting.

Same goes for the coverage report request.

Thanks

Nicola Foot DipRCPath| Viapath
Operations Lead, Cancer Genetics
Genetics Department|5th Floor Tower Wing| Guy's Hospital| London SE1 9RT
0207 188 1716
nicola.foot@viapath.co.uk<mailto:nicola.foot@viapath.co.uk>
www.viapath.co.uk<http://www.viapath.co.uk/>

________________________________

**Comment by woook** [comment]
Taken to R&D.
