### ISSUE TITLE
Sample missing from Ingenuity

### ISSUE THREAD

**Issue by sophiemarks** [woook/moka-fe#275]
Hi,

One CM sample on the lastest run (NGS183) has not appeared in Ingenuity, isn't in the RPKM output and doesn't have a coverage file.
#158509. 

Please can you let me know if there's a problem with this sample?

Sophie

**Comment by aledj2** [comment]
Hi Sophie,

This sample isn't in the samplesheet for the run. Are you sure it was put on that run (170904)?

(We removed the patient info from your issue to preserve confidentiality)

**Comment by aledj2** [comment]
Wasn't on run
