### ISSUE TITLE
Samples to put back into Ingenuity

### ISSUE THREAD

**Issue by rachaelmein** [woook/moka-fe#277]
Please can you put these 3 samples back into Ingenuity please;
NGS175A_05_182569_VJ_CMCMD
NGS179B_19_185018_VJ_CMCMD
NGS167_05_179640_DM_CMCMD

**Comment by aledj2** [comment]
they are all in ingenuity but sorry I shared with Wook not interpretation requests - wook to share

**Comment by woook** [comment]
Shared with Rachael.
