### ISSUE TITLE
Anaysis for TTN in DNA Nexus

### ISSUE THREAD

**Issue by rachaelmein** [woook/moka-fe#278]
I have 34 samples that I would like to analyse TTN in.  The majority will need to be run through DNA Nexus as they are old data.  FASTQ file are saved on the External Hard Drive called "Illumina Run Data" in a folder called "TTN samples for Ingenuity".
However some have already gone through DNA Nexus and I have indicated these on the list attached (I couldn't attach it so it is saved here P:\DNA LAB\Current\NMD_nextgen\TTN Analysis Sept 17.xlsx).  However I will need coverage reports for these.
We don't currently have a  Bed file solely for TTN so if it is quicker you could use the Pan1464.  This will show load of regions of low coverage as there are genes on that bed files that are not in those older panels but I can deal with that.
If you could give me an estimate of when this will be done that will be very helpful as I have some clinicians waiting to make patients appointments for when this data is analysed.
Many thanks

**Comment by aledj2** [comment]
Hi Rachael, These will be done today and shared with interpretation_request ingenuity account probably overnight. 
I'm running everything through the pipeline again.
I'll try to remember the download the coverage reports tomorrow but please chase them.
Aled
