### ISSUE TITLE
WES Request - list of patients from Moka

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [woook/moka-fe#283]
I would like a list to be pulled from Moka containing all cases that have had the epilepsy panels done and are marked as complete.
Panels are Pan670, Pan1307, Pan502, Pan1021, Pan671, and Pan1431.
In some cases the epilepsy panel is part of a larger patient specific primary/secondary panel.

Can the list contain PRU, Lastname, Firstname, DoB, Referrer, Panel, and Test Result please.

Cheers, /Matt

Cheers,
 
/Matt

**Comment by andyb3** [comment]
Query performed and results sent to @MattiasJanssonviapath
