### ISSUE TITLE
Ingenuity sample sharing

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [woook/moka-fe#284]
Hi guys,

Can we have the following round of samples shared with us in Ingnuity please.
170913_NB551068_0059_AHLL5VBGX3_NGS181B_WES16

Cheers, /Matt

**Comment by woook** [comment]
Hi Matt - do you want all 33 WES16 patients?

**Comment by MattiasJanssonviapath** [comment]
Hi,

We have already gotten the first 11 of WES16, so if I could get the other 22 that would be great.
170906_NB551068_0058_AH3VWHBGX3_NGS181A_WES16 - we have already
170913_NB551068_0059_AHLL5VBGX3_NGS181B_WES16 - we don't have
170918_NB551068_0061_AHLMCVBGX3_NGS181C_WES16 - we don't have
Cheers,
/Matt

**Comment by woook** [comment]
Done.
