### ISSUE TITLE
Generic Ingenuity account

### ISSUE THREAD

**Issue by anmolen** [woook/moka-fe#287]
I wanted to transfer samples (NGS187A GSD MMA UCD) but some looks like single entry/ some duplicated / some triplicated????

**Comment by aledj2** [comment]
Hi, 

We know why some were duplicated, this was expected and I'll delete the older entries. However, before I do this can you confirm you have already deleted sample 18 (187280) from the generic account please.

We are also investigating the triplicated cases so if possible please just share these with the analyst and do not delete from the generic account whilst Ingenuity investigate (samples 2 and 17).

**Comment by anmolen** [comment]
Dear,
I did not delete any samples of NGS187A. Maybe somebody else??

  Thank you
                           Aneta
Aneta Molenda| Viapath
Registered Clinical Scientist
Molecular Genetics
5th Floor Tower Wing |Guy's Hospital| London | SE1 9RT
020 7188 1714
020 7188 7273 (Fax)
aneta.molenda@viapath.co.uk<mailto:aneta.molenda@viapath.co.uk>
www.viapath.co.uk<http://www.viapath.co.uk/>
GSTS and KingsPath are now Viapath. New brand, same commitment to transforming pathology services.
Find out more at www.viapath.co.uk/change<http://www.viapath.co.uk/change>.

**Comment by anmolen** [comment]
Dear,
Please see Rachael reply.
                Thank you
                      Aneta
Aneta Molenda| Viapath
Registered Clinical Scientist
Molecular Genetics
5th Floor Tower Wing |Guy's Hospital| London | SE1 9RT
020 7188 1714
020 7188 7273 (Fax)
aneta.molenda@viapath.co.uk<mailto:aneta.molenda@viapath.co.uk>
www.viapath.co.uk<http://www.viapath.co.uk/>
GSTS and KingsPath are now Viapath. New brand, same commitment to transforming pathology services.
Find out more at www.viapath.co.uk/change<http://www.viapath.co.uk/change>.
____________________________________________
From: Mein Rachael
Sent: 03 October 2017 13:58
To: Molenda Aneta; Marks Sophie
Subject: RE: RE:

Dear Aneta
You don’t need the bioinformations to do this just delete any duplicated samples as they will all be the same.  I think this has occurred because the Pan number was wrong on the sample sheet for 2 samples so when it was corrected it possibly initiated analysis again for all samples.  Pre ingenuity analysis it is just a vcf file and therefore there should be no difference between the duplicates.

Rachael
________________________________

**Comment by aledj2** [comment]
Ok thanks.
Rachael is right, that is why the samples were duplicated. I have deleted all files from the first run. If any files are missing then please ask us to re-import.
I will delete any duplicated files once Ingenuity have investigated why files were triplicated.
