### ISSUE TITLE
WES coverage report error

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [woook/moka-fe#293]
NGS Test IDs 432 and 668 returns an error message when trying to create coverage reports

Cheers, /Matt

**Comment by aledj2** [comment]
Hi Matt, can you try to make the report for test 432 please

**Comment by MattiasJanssonviapath** [comment]
Hi Aled,

Yes, it worked! Got a message that one gene symbol was really a phenotype and was not included.

Is testID668 also ready to go?

Cheers,

/Matt

**Comment by aledj2** [comment]
cool, 668 isn't ready yet but hopefully will be soon. will let you know.

**Comment by aledj2** [comment]
ok, try 668 now.

**Comment by MattiasJanssonviapath** [comment]
Yep, worked.

Cheers, /Matt
