### ISSUE TITLE
WES gene panel list

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [woook/moka-fe#294]
Can I have a list of all inhouse panels available for selection during the WES request process (with lists of genes), please. Excel table or similar is fine.

Cheers, /Matt

**Comment by woook** [comment]
Hi Matt – is this for ISO?

**Comment by MattiasJanssonviapath** [comment]
Hi Wook,

No it's a request from Deborah, see forwarded email. For PanelApp submission if suitable.

Cheers,

/Matt

**Comment by woook** [comment]
As discussed, we will generate a list of panels & pan numbers for you.

Please tell Deborah that once it's been decided what to send to PanelApp, you should get back in  touch as we can interact directly with the PanelApp team.


Thanks,


Wook

________________________________

**Comment by andyb3** [comment]
@woook to discuss Deborah

**Comment by andyb3** [comment]
Added to smartsheet

**Comment by woook** [comment]
Superseded by PanelApp development.
