### ISSUE TITLE
Annotate VCFs with homozygous LOF from East London Genome Project

### ISSUE THREAD

**Issue by woook** [woook/moka-fe#298]
http://www.genesandhealth.org/research/scientific-data-downloads

VCF attached (WARNING GENOME BUILD 38, GRCh38)

[all_LOFs_ELGH.03March2017.gatk_PASS_samtools_v3_intersection.discordant_genotypes_missing.GRCh38.VEP_V85.having_fixed_variants_in_multiple_genes.chr1_fixed.txt_0.gz](https://github.com/woook/moka-fe/files/1361942/all_LOFs_ELGH.03March2017.gatk_PASS_samtools_v3_intersection.discordant_genotypes_missing.GRCh38.VEP_V85.having_fixed_variants_in_multiple_genes.chr1_fixed.txt_0.gz)

Paper
[474.full.pdf](https://github.com/woook/moka-fe/files/1361967/474.full.pdf)

**Comment by andyb3** [comment]
Added to smartsheet

**Comment by woook** [comment]
Will require custom annotation. Park until after GATK4 (and a new variant annotator)
