### ISSUE TITLE
WES coverage report comment

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [woook/moka-fe#299]
Hi guys,

Can we have a line added to the bottom of the coverager report saying something along the line of 'More detailed information regarding the coverage of a gene can be obtained by contacting the lab/bioinformatics team'

Cheers, /Matt

**Comment by aledj2** [comment]
@woook @MattiasJanssonviapath @SueLillis
What do you think of:
Please contact the laboratory if more specific gene coverage information is required

**Comment by MattiasJanssonviapath** [comment]
That works for me. /Matt

**Comment by SueLillis** [comment]
I'm happy with that too

**Comment by aledj2** [comment]
A statement will be on reports from now onwards
