### ISSUE TITLE
Ingenuity - sample missing

### ISSUE THREAD

**Issue by helenstorey** [woook/moka-fe#303]
Hi

I just logged onto Ingenuity to analyse a batch of samples and have noticed one is missing, so if it could be put onto the system, that would be great thanks.  The coverage report and RPKM data are there, just not the sample file in Ingenuity.

The sample is:

NGS186_17_187794_LH_ALP_Pan1451_S17_R1_001.refined

Thanks very much
Helen

**Comment by AmyAmelia** [comment]
Sample should now be in the interpretation request account.
