### ISSUE TITLE
Sample to share to Ingenuity interpretation account

### ISSUE THREAD

**Issue by rachaelmein** [woook/moka-fe#305]
Please can you add sample NGS188B_78_188426_MW_BRCAv2_Pan1449 to ingenuity.

This one is missing from my analysis but as I do it as a batch I have only just realised.  I don't know if this one was in ingenuity orignially or not.  It is a but odd that I would have missed it as I did them in order??

**Comment by AmyAmelia** [comment]
Hi Rachael,

This sample should now be back in ingenuity, in the interpretation request pool. let us know if there are any further problems.

**Comment by rachaelmein** [comment]
The sample has not appeared in the Ingenuity interpretation account?

**Comment by AmyAmelia** [comment]
My apologies, I sent it to Wook's email. Have resent it to the interpretation account. it should be there in a few minutes.
