### ISSUE TITLE
HapMap data for CMCMD panel

### ISSUE THREAD

**Issue by rachaelmein** [woook/moka-fe#309]
I need to include HapMap data for the CM_CMD panel validation form.  I thought we had done this but I cant find it as it may have been done via NextGene.

Would it be possible to pull out data for the HapMap sample for Panel1464 fairly urgently?  I just need the summary info you have given me previously.
Sample name is NGS144_21_136819_NA12878_CMCMD

Many thanks
Rachael

**Comment by aledj2** [comment]
email sent
