### ISSUE TITLE
Linux instal

### ISSUE THREAD

**Issue by nfoot** [woook/moka-fe#316]
Please can we have one of our 4th floor Cancer Genetics King's computers converted to a dual Windows/Linux machine and any necessary software installed  so we can run a manual pipeline similar to the one we used for the Swift EGFR pathway panel. It needs to be a mirrow of the one in my office. Can the two machines be linked together in someway so we can easily share data?
Please liaise with me and Gillie for details of PC etc.
Thanks
Nicky

**Comment by aledj2** [comment]
Hi Nicky, I saw Nahid in the lift this morning. she said they only need the linux machine for viewing BAM files. Is this the case? 
We generally try to avoid having something running on multiple systems as it becomes very difficult to maintain multiple systems with the same versions of tools/software etc. 
We could install a BAM viewer and create a shared network drive with them using either a windows or linux machine but I'm not sure about installing the amplivar pipeline.

**Comment by nfoot** [comment]
Hi Aled

No it is not the case.

Gillie wanted to be able to run the manual bioinformatics pipeline for Swift 56 locally rather than up here.

If that is not feasible due to maintaining two separate systems then she at least needs to be able to view the BAM files...

Nicola Foot DipRCPath| Viapath
Operations Lead, Cancer Genetics
Genetics Department|5th Floor Tower Wing| Guy's Hospital| London SE1 9RT
0207 188 1716
nicola.foot@viapath.co.uk<mailto:nicola.foot@viapath.co.uk>
www.viapath.co.uk<http://www.viapath.co.uk/>

________________________________

**Comment by aledj2** [comment]
I installed team viewer and IGV
