### ISSUE TITLE
URGENT - samples missing off ingenuity

### ISSUE THREAD

**Issue by helenstorey** [woook/moka-fe#320]
Hi

If possible, can i have the following samples put onto Ingenuity ASAP (sorry, there's a kidney donor on the run):
NGS190_07_189212_PC_ALP_Pan1451_S7_R1_001
NGS190_05_187719_NH_ALP_Pan1451_S5_R1_001

The coverage reports are there, they're just not on ingenuity.
Many thanks

**Comment by aledj2** [comment]
They should be there now.
Thanks,
Aled

**Comment by helenstorey** [comment]
Thanks very much!
