### ISSUE TITLE
NGS NEQAS Scheme Data

### ISSUE THREAD

**Issue by rachaelmein** [woook/moka-fe#330]
We have run a NEQAS sample for the pilot NGS scheme on the FH panel.  
Sample is NGS190_35_189251_PR_FH_Pan1453

Please could we have the;
VCF file
BED file
FASTQ file compressed in the GNU zip format
BAM file
Many thanks
Rachael

**Comment by aledj2** [comment]
I wasn't sure where to put them so the files are currently in P:\DNA LAB\R&D\171030_NEQAS
Feel free to move or suggest a better place for me to move it to.
They're quite big files so may have filled up the network drive.
Aled

**Comment by woook** [comment]
Hi Rachael

Can we submit an exome as well as FH this year please?

Thanks,

Wook
