### ISSUE TITLE
URGENT - Custom coverage report PRU279727

### ISSUE THREAD

**Issue by RachaelIrwinViapath** [woook/moka-fe#332]
Please can a custom coverage report be produced for PRU 279727:01, showing only the Primary panel genes (the Secondary panel was not analysed due to identification of a C5 variant in the Primary panel). It's urgent as the report is otherwise ready for authorisation. Thanks!

**Comment by aledj2** [comment]
That's in the coverage reports folder - I've overwritten the existing report.
