### ISSUE TITLE
WES - Average coverage for new panel of genes

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [woook/moka-fe#336]
Hi guys,

Can I have the average coverage for the list of genes I have to email since I can't attach it here, please?

Cheers, /Matt

**Comment by AmyAmelia** [comment]
Hi Matt, 
Can you please send us through the list of genes. I can not locate the email.
Thanks
Amy

**Comment by AmyAmelia** [comment]
See document attached to email.
