### ISSUE TITLE
Upload files to Ingenuity & Share with Team WES?

### ISSUE THREAD

**Issue by SueLillis** [woook/moka-fe#338]
Please can the WES files from the following runs be shared with us?

171018_NB551068_0072_AHTCNHBGX3_NGS189A_WES16_WES19

171013_NB551068_0070_AHTGT2BGX3_NGS187C_WES18
171011_NB551068_0069_AHT3GTBGX3_NGS187B_WES14_WES18

Many thanks!

**Comment by SueLillis** [comment]
.

**Comment by AmyAmelia** [comment]
Done
