### ISSUE TITLE
Script to reformat clingen bed files

### ISSUE THREAD

**Issue by woook** [woook/moka-fe#339]
Create script that can be automated to converted ClinGen dosage sensitivity BED files into BED DETAIL files with colour coding instead of a numerical value for the haploinsufficiency/triplosensitivity score.

The two files are found
ftp://ftp.ncbi.nlm.nih.gov/pub/dbVar/clingen/ClinGen_haploinsufficiency_gene.bed
ftp://ftp.ncbi.nlm.nih.gov/pub/dbVar/clingen/ClinGen_triplosensitivity_gene.bed

They are updated daily.

The output should be a single BED DETAIL file deposited on the stickie server along with the other BED files.

We want the script to run daily.

**Comment by andyb3** [comment]
Added to smartsheet

**Comment by woook** [comment]
Suggested colour scheme:

haplo:
3 - red
2 - light red
1 - very light red
0 - yello
30 - grey (mid)

triplo:
3 - blue
2 - light blue
1 - very light blue
0 - yello


You should be able to very easily tell the difference between 3s & 2s (more so than 2s & 1s)

**Comment by aledj2** [comment]
any idea what a score of 40 means (and what colour it should be)

**Comment by aledj2** [comment]
How do you want the files named? The script to make the bedfiles is done - need to work out how to run it daily eg renaming the old version (if required)

**Comment by aledj2** [comment]
obsolete - done by clingen
