### ISSUE TITLE
WES: Unable to generate coverage reports

### ISSUE THREAD

**Issue by hkuoppamaa** [woook/moka-fe#340]
![hk coverage report error](https://user-images.githubusercontent.com/31348002/32365244-c3e736a2-c081-11e7-828e-b7a9cdedfcba.JPG)

I'm still unable to generate coverage reports in Moka. However, the error message I get has changed. Could someone look into this please?

**Comment by aledj2** [comment]
Hi Heidi, that's progress -  it's a different error message! I know what the fix is so will get onto it.

**Comment by aledj2** [comment]
In the mean time if you need the coverage report doing send me the NGS test ID and the panels to be included on the report

**Comment by hkuoppamaa** [comment]
Cheers very much Aled!

**Comment by aledj2** [comment]
the code to do this has been done - it'll be rolled out soon. Will close this issue for now
