### ISSUE TITLE
WES results page quality of life

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [woook/moka-fe#342]
Hi guys,

When having more variants than fits the page we need to scroll down to write the comments for each variant. After updating the comments for a variant and closing the comments window, the list re-sets to the top requiring us to scroll down again to access the next variant. Can the list be adjusted to not re-set to the top but rather stay in the same frame?

Fure quality of life but would be nice to aviod the scrolling.

Cheers, /Matt

**Comment by andyb3** [comment]
I don't think there's an easy way to fix this because the page has to refresh after the comment has been updated, so going to close this issue for now. Sorry!
