### ISSUE TITLE
NGS192 coverage file missing

### ISSUE THREAD

**Issue by helenstorey** [woook/moka-fe#346]
Hi
I'm missing a coverage file off Run NGS192 for the following patient:

NGS192_10_190263_RC_ALP_Pan1451_S10_R1_001.refined - Genotype

I was just wondering if it could be found!

Many thanks
Helen

**Comment by aledj2** [comment]
That should be there now.
thanks,
Aled

**Comment by helenstorey** [comment]
Thanks very much
H
