### ISSUE TITLE
URGENT ARRAYS - track needed in UCSC browser

### ISSUE THREAD

**Issue by sbint** [woook/moka-fe#354]
URGENT ARRAYS:
Region - Chr10:102,969,334-103,416,646 - Under the GuysInfo track in the UCSC browser please can a track be added in this region to say Report Dups  - these are associated with SHFM3 OMIM: 246560

**Comment by woook** [comment]
BED file created, committed and uploaded to server.
https://github.com/woook/datasets/commit/e8499aeffecae191b90b682f3da283356f7ec4e4
This is a BED file outside Moka, closing issue.
