### ISSUE TITLE
Ingenuity user guide 

### ISSUE THREAD

**Issue by aledj2** [woook/moka-fe#361]
Create or add to a document to describe maintenance issues for ingenuity eg renewing generic user account passwords

**Comment by aledj2** [comment]
change request submitted

**Comment by aledj2** [comment]
a few weeks ago the password expired, after re-reading the email I think this was caused by someone requesting a new password, or after forgetting the password rather than it expiring

**Comment by aledj2** [comment]
actually... the email rule I set up was for emails with the subject "password is expiring" (or similar). have emailed qiagen

**Comment by andyb3** [comment]
Added to smartsheet
