### ISSUE TITLE
TTN analysis

### ISSUE THREAD

**Issue by rachaelmein** [woook/moka-fe#370]
I would like to request that this "old" samples be process via DNA Nexus using Pan1464 as we have been asked to look at TTN;
NGS118a_07_164559_IB_CM 
FASTQ files are on Pluto

Thanks
Rachael

**Comment by aledj2** [comment]
Just set this going through the pipeline. Last time it took 2-3 hours so keep an eye out in the interpretation request ingenuity account after lunch.

**Comment by rachaelmein** [comment]
Hi Aled
Please could we have coverage reports for the TTN sample (NGS118a_07_164559_IB_CM) you put through the pipeline last week?
Many thanks
Rachael


________________________________

**Comment by rachaelmein** [comment]
Hi Rachael,


I've put it in the folder P:\DNA LAB\Current\NGS worksheets\TTN Sept 2017.


Thanks


Aled

Aled Jones
Clinical Bioinformatician
Genetics Laboratories| 5th Floor Tower Wing | Guy's Hospital | Great Maze Pond | London | SE1 9RT
Tel: 02071881701
Email: aledjones@nhs.net
________________________________
From: Mein Rachael <Rachael.Mein@viapath.co.uk>
Sent: 21 November 2017 10:53
To: 'woook/moka-fe'
Cc: JONES, Aled (GUY'S AND ST THOMAS' NHS FOUNDATION TRUST); Marks Sophie
Subject: RE: [woook/moka-fe] TTN analysis (#370)

Hi Aled
Please could we have coverage reports for the TTN sample (NGS118a_07_164559_IB_CM) you put through the pipeline last week?
Many thanks
Rachael


________________________________
