### ISSUE TITLE
WES coverage report on wrong run

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [woook/moka-fe#372]
Hi Aled,

Another case where the coverage report is generated on an old failed run. I need TestID441 coverage report on data from the NGS169B_08_162256_TL_WES14_Pan493_S4_R1_001.refined run, please.
Pan628 and Pan629.

Cheers, /Matt

**Comment by aledj2** [comment]
Have re-imported the coverage data and generated the coverage report on the S drive. The old one was moved into the 'don't use' folder. Let me know if you don't think it's the correct data still
