### ISSUE TITLE
Sample back in

### ISSUE THREAD

**Issue by jomccauley** [woook/moka-fe#373]
Hello,

Please could patient IT 185349 PRU: 440393 NGS187A be put back in to Ingenuity for extra analysis

Thanks
Jo

**Comment by aledj2** [comment]
should be shared with interpretation request account in the next few minutes

**Comment by jomccauley** [comment]
Sorry, the sample was

NGS187A_03_187917_IT_CMCMD

Thanks
Jo
________________________________

**Comment by aledj2** [comment]
no worries, this has now been added. please delete the previous one from ingenuity

**Comment by jomccauley** [comment]
Great
Thanks
Jo

________________________________

**Comment by jomccauley** [comment]
The sample that was added yesterday is inactive.  Is this because there are too many samples in there?  Is there a way of making it active so I can analyse it?
Thanks
Jo

________________________________

**Comment by aledj2** [comment]
Yea, I think samples will need to be deleted in order to make samples active.
