### ISSUE TITLE
DNA NGSEQ Panels

### ISSUE THREAD

**Issue by rachaelmein** [woook/moka-fe#375]
Here is a list of what is required to bring these panels into service;
(1) BED Files to be made;
DNA NGSEQ1 Pan1157 for coverage
DNA NGSEQ1 Pan1455 for RPKM
DNA NGSEQ2 Pan1158 for coverage
DNA NGSEQ2 Pan1456 for RPKM
DNA NGSEQ3 Pan1159 for coverage
DNA NGSEQ3 Pan1457 for RPKM

(2) Process following samples through analysis pipeline (as for custom panels)
DNA NGSEQ1 14 samples on NGS171B
NGS171B_33_103907_SR_NGSEQ1_Pan1157
NGS171B_34_104647_CB_NGSEQ1_Pan1157
NGS171B_35_104817_JC_NGSEQ1_Pan1157
NGS171B_36_105361_CR_NGSEQ1_Pan1157
NGS171B_37_105362_JL_NGSEQ1_Pan1157
NGS171B_38_166041_BS_NGSEQ1_Pan1157
NGS171B_39_168369_GR_NGSEQ1_Pan1157
NGS171B_41_172842_JF_NGSEQ1_Pan1157
NGS171B_42_174248_AB_NGSEQ1_Pan1157
NGS171B_43_175057_AP_NGSEQ1_Pan1157
NGS171B_44_175226_BP_NGSEQ1_Pan1157
NGS171B_45_175318_JS_NGSEQ1_Pan1157
NGS171B_46_177940_KW_NGSEQ1_Pan1157
NGS171B_47_178716_VP_NGSEQ1_Pan1157

DNA NGSEQ2 37 samples on NGS171B
NGS171B_49_59830_JS_NGSEQ2_Pan1158
NGS171B_50_66671_DL_NGSEQ2_Pan1158
NGS171B_51_76215_SB_NGSEQ2_Pan1158
NGS171B_52_77789_BL_NGSEQ2_Pan1158
NGS171B_53_85196_FM_NGSEQ2_Pan1158
NGS171B_54_86374_HB_NGSEQ2_Pan1158
NGS171B_55_89752_JS_NGSEQ2_Pan1158
NGS171B_57_97714_KD_NGSEQ2_Pan1158
NGS171B_58_101050_KC_NGSEQ2_Pan1158
NGS171B_59_107938_HA_NGSEQ2_Pan1158
NGS171B_60_109003_RF_NGSEQ2_Pan1158
NGS171B_61_116285_AT_NGSEQ2_Pan1158
NGS171B_62_127151_YD_NGSEQ2_Pan1158
NGS171B_63_131434_CO_NGSEQ2_Pan1158
NGS171B_65_137084_RB_NGSEQ2_Pan1158
NGS171B_66_137627_OH_NGSEQ2_Pan1158
NGS171B_67_141842_MP_NGSEQ2_Pan1158
NGS171B_68_145321_CS_NGSEQ2_Pan1158
NGS171B_69_153089_AH_NGSEQ2_Pan1158
NGS171B_70_154607_JD_NGSEQ2_Pan1158
NGS171B_73_162003_ML_NGSEQ2_Pan1158
NGS171B_74_165164_DH_NGSEQ2_Pan1158
NGS171B_75_166583_NL_NGSEQ2_Pan1158
NGS171B_76_166803_CC_NGSEQ2_Pan1158
NGS171B_77_167227_TG_NGSEQ2_Pan1158
NGS171B_78_167712_AT_NGSEQ2_Pan1158
NGS171B_79_168077_RC_NGSEQ2_Pan1158
NGS171B_81_168571_NS_NGSEQ2_Pan1158
NGS171B_83_170464_PG_NGSEQ2_Pan1158
NGS171B_84_171554_KD_NGSEQ2_Pan1158
NGS171B_85_173229_OJ_NGSEQ2_Pan1158
NGS171B_86_173692_SV_NGSEQ2_Pan1158
NGS171B_87_174387_MG_NGSEQ2_Pan1158
NGS171B_89_176776_FD_NGSEQ2_Pan1158
NGS171B_90_180095_ID_NGSEQ2_Pan1158
NGS171B_93_136819_NA12878_NGSEQ2_Pan1158
NGS171B_94_114242_AH_NGSEQ2_Pan1158

DNA NGSEQ3 10 samples on NGS175B
NGS175B_35_162056_RG_NGSEQ3_Pan1159
NGS175B_36_167201_SW_NGSEQ3_Pan1159
NGS175B_37_174105_LC_NGSEQ3_Pan1159
NGS175B_38_148823_PP_NGSEQ3_Pan1159
NGS175B_39_176213_MB_NGSEQ3_Pan1159
NGS175B_40_172579_GM_NGSEQ3_Pan1159
NGS175B_41_160662_BM_NGSEQ3_Pan1159
NGS175B_42_155445_DM_NGSEQ3_Pan1159
NGS175B_43_163297_DG_NGSEQ3_Pan1159
NGS175B_44_164315_DN_NGSEQ3_Pan1159

(3) Summary Info (Sensitivity/specificity/false neg/false pos etc) for NA12878 Sample
DNA NGSEQ2 - Sample identifier is NGS171B_93_136819_NA12878_NGSEQ2_Pan1158
The library prep failed for NA12878 for DNA NGSEQ1 and DNA NGSEQ3 so this will be repeated in due course.

The order of priority for each panel is;
1) DNA NGSEQ2
2) DNA NGSEQ1
3) DNA NGSEQ3

Thank you
Rachael

**Comment by aledj2** [comment]
awaiting code review

**Comment by woook** [comment]
Job submitted.

Need to organise training for monogenics scientist to:
- run benchmarking and assess sensitivity
- assess coverage and look at BAM files in IGV
