### ISSUE TITLE
NGS157 'old' sample

### ISSUE THREAD

**Issue by sophiemarks** [woook/moka-fe#381]
I would like to request that this "old" samples be process via DNA Nexus using Pan1464 as we have been asked to look at TTN;
NGS157B_31_155867_JD_CM
FASTQ files should be on the cloud??

Thanks
Sophie

**Comment by aledj2** [comment]
being processed - should take ~ 2 hours.  don't close until download the coverage report (exon level)

**Comment by aledj2** [comment]
coverage report is in P:\DNA LAB\Current\NGS worksheets\TTN Sept 2017
