### ISSUE TITLE
WES panel - list of genes with coverage

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [woook/moka-fe#385]
Hi,

Can I have the list of genes and average coverage for Pan397 and Pan1144, please.

Cheers, /Matt

**Comment by aledj2** [comment]
Hi Matt,
What exactly do you need and what is it for? 
This will inform if I need to calculate confidence intervals and how to select which samples to include in the calculations.
Thanks,
Aled

**Comment by MattiasJanssonviapath** [comment]
Hi Aled,
This is for making an update to the panels. Just the average coverage from https://mokaguys.shinyapps.io/covapp/ please. Nothing fancy.
Cheers, /Matt
