### ISSUE TITLE
Create a copy of a NGS Test result for when a sample is re-run

### ISSUE THREAD

**Issue by aledj2** [woook/moka-fe#387]

**Comment by aledj2** [comment]
would this just create a new copy of the NGS Test result, with the internal patient id, DNA, referralID, Panels, date requested,bookby, result build,

**Comment by aledj2** [comment]
the failed test would need to change the status to 4 (or something else)

**Comment by aledj2** [comment]
The SQL written by upload agent scrip updated (to update the pipeline version) would need to have something like "where status is not = complete or repeated"

**Comment by andyb3** [comment]
use patient page?
