### ISSUE TITLE
Ingenuity cases inactive again

### ISSUE THREAD

**Issue by nfoot** [woook/moka-fe#391]
Morning
The oncology run 31 is inactive this morning.

Please can this be addressed ASAP as last week this resulted in 4 patient reports being delayed by a day.

Thanks
Nicky

**Comment by AmyAmelia** [comment]
Should be good to go now. Please can you ensure you and your team, also have a tidy up you the general oncology and personal accounts. 

Thank 
Amy

**Comment by nfoot** [comment]
Thanks Amy

I have reminded the team to delete everything once it is analysed.

My account and the general account should be fine...

N

Nicola Foot DipRCPath| Viapath
Operations Lead, Cancer Genetics
Genetics Department|5th Floor Tower Wing| Guy's Hospital| London SE1 9RT
0207 188 1716
nicola.foot@viapath.co.uk<mailto:nicola.foot@viapath.co.uk>
www.viapath.co.uk<http://www.viapath.co.uk/>

________________________________
