### ISSUE TITLE
Vardict not showing ex19 indel

### ISSUE THREAD

**Issue by nfoot** [woook/moka-fe#393]
ONC31-02-EK5562-1737688

This sample shows EGFR c.2235_2249del 4.15% an c.2252C>T 4.15% on Varscan
This is in exon 19 and likely to be an indel
The Vardict VCF has been uploaded and the indel is not present.
I am about to have a look at the BAM file.
Please can Amy help me out with this? :)
Nicky

**Comment by AmyAmelia** [comment]
Ingenuity wont validate a vcf if an indel is the first (or only variant). Sample now shared with nicky.
