### ISSUE TITLE
bioinformatics help needed for variant assessment

### ISSUE THREAD

**Issue by jocampbell** [woook/moka-fe#394]
I need some help with a few tools for variant assessment - we wondered if Amy would have any time to help with this?  See the final page of the attached (hopefully) variant analysis useful info document.

thanks

Jo

**Comment by andyb3** [comment]
Added to smartsheet

**Comment by woook** [comment]
Will close for now until there is greater consensus on which additional tools to use.

**Comment by jocampbell** [comment]
Hi Wook,

Please can we have a discussion before you close this?  No-one has even been to ask me what I needed yet.

Thanks

Jo

Joanna Campbell PhD | Viapath
Clinical Scientist
Molecular Genetics
5th Floor Tower Wing |Guy's Hospital| London | SE1 9RT
020 7188 1714 (Tel)
020 7188 1697 (Fax)
joanna.campbell@viapath.co.uk<mailto:joanna.campbell@viapath.co.uk>
joanna.campbell3@nhs.net<mailto:joanna.campbell3@nhs.net>
A unique partnership of clinical, scientific and operational expertise, on a mission to transform pathology services in the UK.

Find out more at www.viapath.co.uk<http://viapath.us10.list-manage.com/track/click?u=650308f65b655be63608468c8&id=a65cf78aed&e=171a097318>, follow us on Twitter @ViapathUK<http://viapath.us10.list-manage1.com/track/click?u=650308f65b655be63608468c8&id=c342df3db0&e=171a097318> and connect with us on LinkedIn<http://viapath.us10.list-manage.com/track/click?u=650308f65b655be63608468c8&id=bbbdf7ad55&e=171a097318>.

**Comment by woook** [comment]
Sure - there is a talk at ACGS this year which will be informative. Are you attending?
