### ISSUE TITLE
WES coverage report request

### ISSUE THREAD

**Issue by RachaelIrwinViapath** [woook/moka-fe#401]
Hi,
Please could I have a bespoke coverage report for the following WES case:
NGS185C_28_178467_ER_WES17
Just to include Pan1613 (this is a tertiary panel containing only ACVR1 and GNAS, as these genes were prioritised by the clinician and we found a Class 5, so the remaining Primary and Secondary panel genes were not analysed).
Thanks,
Rachael

**Comment by aledj2** [comment]
Hi Rachael, Do you have a NGS test ID?
Can you raise future issues in our new helpdesk @ https://github.com/moka-guys/helpdesk/issues

**Comment by RachaelIrwinViapath** [comment]
Hi Aled,
Sorry, I forgot there was a new helpdesk, I just used the URL from the SOP!
Which is the NGS test ID - do I get this from Ingenuity? The sample ID is 9326968 and the Barcode is file-F8PvX0Q0zZPkZkKKGF2Ygzyk but not sure if either of those are what you need, sorry.
Thanks!

**Comment by aledj2** [comment]
The NGS test ID is from Moka, is a 3 digit number, in this case 729. I was able to find it from the DNA number but in the future it'd be best to provide this in case the same DNA sample is used for a repeat test. 

Have made the report and put it in the usual place - please check!

**Comment by RachaelIrwinViapath** [comment]
Ah, I see it now, thanks - it's amazing the things you don't "see" when you don't use them routinely, sorry about that! I'll know what you need in future.

Thanks for making the report - I'll check it now.

Rachael

________________________________
