### ISSUE TITLE
Switch everything that uses chromeurl in firefox module to use firefoxurl

### ISSUE THREAD

**Issue by andyb3** [woook/moka-fe#415]
In Moka there are a some browser links that open using the chromeurl function rather than firefoxurl. When moving to Windows 10 these should be updated to use the firefoxurl function (which is being changed to actually use chrome!)

**Comment by woook** [comment]
rolf

**Comment by andyb3** [comment]
Don't worry about for now, currently the chromeurl links only work on Wook's machine anyway
