### ISSUE TITLE
Problem updating Moka after labelling

### ISSUE THREAD

**Issue by mikecoldwell** [woook/moka-fe#419]
We used to be able to update the comment section of the page 9192 LabelledDNAs. Now there is an error which closes moka each time. "Execution of this application has stopped due to a run-time error. The application can't continue and will be shut down. OK"

**Comment by andyb3** [comment]
Please could you try this again to see if it is now fixed? You will need to restart Moka

**Comment by andyb3** [comment]
This should now be fixed.
