### ISSUE TITLE
Re-analysis of sample

### ISSUE THREAD

**Issue by jomccauley** [woook/moka-fe#467]
Hi

I need to re-analyse the following sample:
189548 NGS191
Please can it be added back into Ingenuity.
Thanks
Jo

**Comment by aledj2** [comment]
Hi Jo,
In the future can you use the https://github.com/moka-guys/helpdesk/issues repo to raise issue please. Also please be careful not to put patient identifiers.
Will look at this now.

**Comment by aledj2** [comment]
All done. Shared with interpretation request account
