### ISSUE TITLE
add referral status of 1199901218 to exclude for wes dashboard (and other scripts?) 

### ISSUE THREAD

**Issue by aledj2** [woook/moka-fe#474]

**Comment by andyb3** [comment]
This would need to be done to `87020 ExomeLab` and `87018 ExomeStatus`

Could edit the following in both forms:

```
'String of referral types to exlude (e.g. Oncology samples) to be inserted into WHERE clause of recordsource
excludeReferrals = "NGSTest.ReferralID <> 1199901217"
```
(Although maybe it would actually be better to change it so that the forms only include the WES referrals, rather than excluding all the other referrals)

**Comment by aledj2** [comment]
code review done. not rolled out yet
