### ISSUE TITLE
Moka booking in

### ISSUE THREAD

**Issue by ClaRomano** [woook/moka-fe#476]
Booking into Moka has become much slower than usual.

**Comment by andyb3** [comment]
Hi Claudia. Sorry to hear that. When did you first notice this issue?

Also we have now switched to using a different repo for issues so please raise future issues here: https://github.com/moka-guys/helpdesk

Thanks,
Andy

**Comment by ClaRomano** [comment]
Hi Andy,
I have noticed this yesterday.

Thanks for the new link.

Claudia

Claudia Romano
Medical Technical Officer 2 | Viapath
Genetics department
5th floor Tower Wing | Guy’s Hospital | London | SE1 9RT
claudia.romano@viapath.co.uk<mailto:claudia.romano@viapath.co.uk>
Tel: +44 (0) 207 181706

**Comment by aledj2** [comment]
Can this be closed now?
