### ISSUE TITLE
Custom coverage report request NGS Test ID 937

### ISSUE THREAD

**Issue by RachaelIrwinViapath** [woook/moka-fe#493]
Hi, please could we have a custom WES coverage report for this patient: JB, DNA 186447, NGS Test ID 937, WES 20. We need a coverage report for the PIGL gene only, as we have found a hom variant in this gene that fits phenotype, and the clinician has said no further analysis of other genes is required. Thanks!

**Comment by AmyAmelia** [comment]
Hi Racheal, 
Please can you add this gene as a tertiary panel, (we are unable to generate coverage reports on individual genes not associated with a panel ID). Following this, Matt or Sue will be able to generate the coverage report from Moka. 

Thanks
Amy
