### ISSUE TITLE
Please can I have an ingenuity account

### ISSUE THREAD

**Issue by cdonaghue** [woook/moka-fe#494]

**Comment by cdonaghue** [comment]
Hi

You need a trial sign up code.  There is a link if you do not have a code but it just takes you to their front page.

Celia

**Comment by AmyAmelia** [comment]
​Apologies Celia, I gave you incorrect information, and we are in fact able to set this up for you. I have created an account for you using your viapath email. ​
Amy

**Comment by cdonaghue** [comment]
thanks
