### ISSUE TITLE
Memo fields in reports are sometimes truncated

### ISSUE THREAD

**Issue by andyb3** [woook/moka-fe#496]
Memo fields in reports are truncated to 255 characters if the record source query uses DISTINCT 

This caused an issue in the FamilyResults_Auto_PGD_Report report when the PGDResultComment was over 255 characters

One solution is to use a DLookup for the field rather than bind it to a field from the query as described in the following article: https://social.msdn.microsoft.com/Forums/office/en-US/6330dbfc-4a1f-4b31-b139-90b6f7ff9327/report-memo-field-truncated-to-255-characters?forum=accessdev

**Comment by woook** [comment]
Make a ServiceNow knowledgebase article explaining this and put a non-visible text box with link to article on the report.
