### ISSUE TITLE
Array Audits

### ISSUE THREAD

**Issue by mikecoldwell** [woook/moka-fe#513]
Further to issue: 572 UnreportedRushArrays #213, please can both the UnreportedRushArrays and the Unauthorised patients audits also contain a column with the initials of the person who raised the test request. Thank you very much
Mike

**Comment by AmyAmelia** [comment]
Hi Mike,
We are no longer using this repo to track requests and issues. Please, can you reraise this issue in the 
https://github.com/moka-guys/helpdesk repo. If you copy and paste the URL to the original issue in the comment section of the new issue Github will link them together, 

Thank you
Amy
