### ISSUE TITLE
NGS reports - Is there a way to see if an NGS report has been authorised?

### ISSUE THREAD

**Issue by woook** [woook/moka-fe#66]

**Comment by woook** [comment]
This may require something in Geneworks that flags a report as an NGS one.
What about the issue of multiple reports for one specimen?

**Comment by AmyAme1ia** [comment]
This issue had been previously been discussed and put on hold. Concerns
where raised regarding how it would work if a NGS test and been completed
and approved, and then a second test is ordered. We could not identify a
way to identify and link an approved report within geneworks to a specific
test.

**Comment by AmyAmelia** [comment]
Now have a tracking system and a method for marking when a report has been authorised. independent of Geneworks.
