### ISSUE TITLE
NGS ordering - can DNA be auto-assigned to test at ordering stage?

### ISSUE THREAD

**Issue by woook** [woook/moka-fe#80]

**Comment by woook** [comment]
If there is more than one DNA, then the latest should be used

**Comment by andyb3** [comment]
Will look at options for this at same time as working on DNA QC

**Comment by AmyAme1ia** [comment]
Need to consider who to implement this, if the most uptodate DNA number is in  gw but not in MOKA. Current method on the patients form in MOKA is to import the selected DNA from geneworks using the 'import form geneworks button'.

**Comment by andyb3** [comment]
This is not required. Discussed with Matt, just going to assign DNA at QC stage.
