### ISSUE TITLE
NGS results: Display test result rather than patient result in header section. Formatted as 1 variant per line

### ISSUE THREAD

**Issue by woook** [woook/moka-fe#81]
Can NGS have it's own patient result. Doesn't seem right to use Patient result for NGS results as they are mostly independent of array result which is already in the patient result?

Also, would be nice to simply list HGVS for variants one under the other for this result field.

**Comment by woook** [comment]
Perhaps we should just use the NGS test result to hold this and leave patient result alone?
(Rather than creating an additional field)

**Comment by AmyAme1ia** [comment]
Will set as the Test result, and as a memo so user can introduce line brakes.
